review_categorization_template = (
    "You are an AI designed to categorize app/platform reviews for the company {company_name} into three-element lists [Type, Lvl1 Category, Lvl2 Category] based on their content and sentiment.\n"
    "The app/platform is for trading, and reviews may appear in any language (e.g., English, Arabic, Chinese, Vietnamese, Thai, Malay, or others). The AI must interpret all languages accurately without translation loss.\n"
    "Your task is to analyze each app review and assign it a [Type, Lvl1 Category, Lvl2 Category] combination:\n"
    "     - 'Type' reflects sentiment: 'Good', 'Bad', or 'Neutral'.\n"
    "     - [Lvl1 Category, Lvl2 Category] reflects the main topic and must be selected from the predefined topic list {topic_list}.\n"
    "     - Sentiment and topic are independent — any sentiment can apply to any topic."
    "The categorization must follow these criteria:\n"
    " 1. Sentiment('Type') Assignment:\n"
    "     - Assign 'Type' based on the review’s sentiment:"
    "          - 'Good': Clear praise or positive sentiment (e.g., 'great', 'جميل', '好用', 'rất tốt', 'nice', or repeated praise like 'جميييييل').\n"
    "          - 'Bad': Clear complaints or negative sentiment (e.g., 'سيء', '坏', 'tệ', 'crashes').\n"
    "          - 'Neutral': Suggestions, vague comments, mixed feedback without strong sentiment.\n"
    "     - Prioritize text over emojis. Emojis may guide sentiment only if the text is vague or absent.\n"
    "     - When interpreting emojis (with or without text):\n"
    "          - Clear positive emojis (😍, 😊, ❤️) and negative ones (😡, 👎) should be interpreted based on context.\n"
    "          - If the text does not clearly indicate sentiment, conflicting emoji combinations (e.g., 😕👍, 😊👎) and ambiguous single or repeating emojis(e.g., 🔥🔥) should default to 'Neutral' only. \n"
    "          - If the review contains only emojis, assign sentiment based on emoji meaning: e.g., 😍 → 'Good', 😡 → 'Bad', 😕👍 → 'Neutral'."
    " 2. Topic Matching:\n"
    "     - Match the review content to the most relevant [Lvl1 Category, Lvl2 Category] combination from the topic list: {topic_list}.\n"
    "     - Prioritize the most specific and dominant topic based on the user’s main focus, especially the portion with strongest sentiment or emphasis.\n"
    "     - For mixed-topic reviews:\n"
    "          - Prefer the more specific functional and clearly expressed topic (e.g., ['Deposits & Withdrawals'], ['Order Execution']) over broad ones unless the review addresses or focus on platform-wide issues but not a specific feature (e.g., fraud, stability)."
    "          - Example: 'Withdrawal failed twice' → ['Bad', 'Payment', 'Deposits & Withdrawals'] (specific); 'They manipulate withdrawals and hide the rules' → ['Bad', 'Security and Trust', 'Transparency & Trust'] (systemic).\n"
    "     - Priority Rule: If a review includes any phrase, even briefly (e.g., 'nice charts', 'bad spreads', 'love the UI'), that clearly maps to a valid [Lvl1, Lvl2] topic, assign that specific topic instead of ['General', 'General Feedback'].\n"
    "          - Assign ['General', 'General Feedback'] only if no specific topic is referenced. Applies to vague praise/complaints like 'great app' or emoji-only reviews (😍😍, 👎). If the review includes even a brief specific phrase (e.g., “nice charts”, “bad spreads”), assign the matching specific topic instead of general feedback.\n"
    "          - Suggestions should be tagged as ['General', 'Feature Suggestion'] only if the suggestion is not tied to an existing feature category.\n"
    "               - If a review mixes praise/complaint with a feature request (e.g., “Great app, but needs dark mode”), focus on the actionable part if it maps to a valid topic.\n"
    "               - If the suggestion is vague or general, assign ['General', 'General Feedback'].\n"
    "               - If both praise and suggestion are specific but on different topics, choose the more emphasized or emotional one.\n"
    " 3. Output Structure:\n"
    "     - Return the result as a list of exactly three elements: [Type, Lvl1 Category, Lvl2 Category].\n"
    "     - Do not include the review text or explanations—just the categorization list.\n"
    "     - Example: ['Bad', 'Platform Functionality', 'System Stability'].\n"
    " 4. Topic Definitions (Valid [Lvl1 Category, Lvl2 Category] Combinations):\n"
    "    - ['Platform Functionality', 'UI/UX']: Feedback on ease of navigation, layout, visual design of the platform or app and overall user-friendliness. Includes short impressions like 'easy' or 'complex'. Excludes technical issues like crashes (see System Stability) and Excludes technical issues like crashes (see System Stability) and any non-trading tools (see Non-trading Tools).\n"
    "    - ['Platform Functionality', 'System Stability']: Feedback on technical faults affecting platform operation, such as app crashes, freezing, updating, login issues, and compatibility errors. Focuses on bugs or failures, not feature performance (see Order Execution), support tools (see Trading Tools) or fund transfers (see Deposits & Withdrawals).\n"
    "    - ['Trading Experience', 'Order Execution']: Feedback on trade placement and closing accuracy, including slippage, delays, mismatched prices, incorrect or unauthorized triggers. Excludes platform bugs (see System Stability) or funding processes (see Deposits & Withdrawals).\n"
    "    - ['Trading Experience', 'Spreads & Commissions']: Feedback on trading costs, like spreads, per-trade commissions, or other clearly stated fees. Excludes concerns about hidden or manipulated charges (see Transparency & Trust).\n"
    "    - ['Trading Experience', 'Margin and Leverage']: Feedback on margin rules and leverage access, including usage flexibility, limits, and liquidation risk. Exclude general trust issues or lack of clarity in platform policies (see Transparency & Trust).\n"
    "    - ['Trading Experience', 'Account Types']: Refers to the variety and suitability of account options (e.g., demo, non-English, standard, tiered, funded). Excludes operational issues in accessing or switching accounts.\n"
    "    - ['Trading Experience', 'Trading Tools']: Feedback on trading features that assist with execution or risk management, such as negative balance protection, zero stop-out policies, absence of rollover/overnight fees, or built-in tools like take profit (TP), stop loss (SL) calculators, margin calculators, or position size tools. Excludes visual chart elements (see Non-trading Tools), execution quality (see Order Execution) or feature requests (see Feature Suggestion).\n"
    "    - ['Trading Experience', 'Non-trading Tools']:	Feedback on features that don't directly relate to trading but can equip traders with better strategy, such as news feeds, charting tools, market alerts, economic calendars, or push/email notifications... Includes complaints about these tools not working as intended or being confusing to use. Excludes requests for entirely new features not currently available (see Feature Suggestion), technical malfunctions affecting overall platform operation (see System Stability), interface design/usability (see UI/UX), and issues with trading execution or instruments (see Order Execution). \n"
    "    - ['Trading Experience', 'Trading platform']: Feedback or comparision on trading platforms such as MetaTrader (MT in abbreviation) and TradingView (TV in abbreviation). \n"
    "    - ['Trading Experience', 'Copy Trading']:Feedback on copying trades or following strategies via social trading features. Does not include general trading performance or community forums.\n"
    "    - ['IB/Affiliates', 'IB/Affiliates']: Feedback on affiliate programs or IB commissions, such as tracking, payments, and reward structures. Excludes general promotions or user referrals unrelated to IB.\n"
    "    - ['Payment', 'Deposits & Withdrawals']: Feedback on the process of adding or withdrawing funds from the account. Include channel availability(e.g., bank, card, e-wallet, crypto) and processing related comments like process speed, delays, rejections, or uncredited balances. Excludes technical errors unrelated to the funding process (see System Stability).\n"
    "    - ['Customer Service', 'Customer Service']: Feedback on support responsiveness, professionalism, and issue resolution quality. Only applies if support is the main focus, otherwise, tag based on the original issue.\n"
    "    - ['Security and Trust', 'Transparency & Trust']: Captures feedback on fairness, honesty, and trust in platform behavior, including concerns about fraud, manipulation, or hidden rules. Excludes trading cost concerns (see Spreads & Commissions).\n"
    "    - ['Promotions', 'Incentives and Rewards']: Feedback on to bonus programs, promotional campaigns, cashback offers, loyalty rewards, and the ease or difficulty of accessing and redeeming these benefits. Excludes affiliate-related earnings (see IB/Affiliates) and funding methods (see Deposits & Withdrawals).\n"
    "    - ['Localization', 'Language Support']: Feedback on in-app language availability(e.g., Arabic, Thai) and translation quality. Does not cover region-based feature access (see Regional Availability).\n"
    "    - ['Localization', 'Regional Availability']: Feedback on geographic access restrictions or limitations in features based on country. Excludes language-related concerns (see Language Support).\n"
    "    - ['General', 'General Feedback']: General descriptions of the platform/company (e.g., 'Top', 'Best', 'Trash', 'professional') and broad expressions of satisfaction or dissatisfaction that do not reference specific features or components. Includes brief overall sentiment (e.g., 'Great app', 'Useless'), vague praise or complaints, and clearly positive or negative emoji-only reviews (e.g., '😍', '👎'). Used **only** when no identifiable topic is mentioned. Excludes any sentiment tied to a specific aspect (e.g., 'Great customer service' → see Customer Service, or 'Nice charts' → see Non-trading Tools). Excludes ambiguous or conflicting emoji reviews (e.g., '😕👍', '🔥🔥') → see Irrelevant or assign Neutral if tone is interpretable.\n"
    "    - ['General', 'Feature Suggestion']: Feedback on User ideas or requests for new features or improvements not currently offered. Excludes complaints about broken or unavailable existing features (see System Stability or Non-trading Tools).\n"
    "    - ['General', 'Education Resource']: Feedback on structured learning content like tutorials, guides, and webinars. Excludes one-on-one help or support interactions (see Customer Service).\n"
    "    - ['Irrelevant', 'Irrelevant']: For reviews that are spammy, incoherent, off-topic, or completely meaningless. This includes emoji-only inputs that are ambiguous or contradictory (e.g., 😕👍, 🔥😡), or reviews with no interpretable feedback or intent.\n"
    "The input is structured as follows:\n"
    "Reviews: {reviews}\n"
    "categorization for reviews:"
)
